package com.ai.career.validation.model;

public enum ValidationErrorCode {
    REQUIRED_FIELD_MISSING,
    UNSUPPORTED_FIELD,
    INVALID_EMAIL,
    INVALID_PHONE,
    INVALID_URL,
    INVALID_NUMBER,
    INVALID_DATE,
    INVALID_OPTION,
    FILE_MISSING,
    FILE_UNREADABLE,
    RESUME_MISSING,
    COVER_LETTER_MISSING,
    PROVIDER_CAPABILITY_MISSING,
    SENSITIVE_FIELD_REQUIRES_REVIEW,
    AI_ANSWER_REQUIRES_REVIEW,
    APPLICATION_STATE_INVALID,
    APPROVAL_REQUIRED,
    DRY_RUN_FAILED,
    EXECUTION_NOT_AUTHORIZED
}
