CREATE TABLE IF NOT EXISTS controlled_application_executions (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    application_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    tenant_id VARCHAR(100) DEFAULT 'default',
    execution_run_id VARCHAR(100),
    preview_id VARCHAR(100),
    confirmation_id VARCHAR(100),
    form_fingerprint VARCHAR(255),
    workflow_status VARCHAR(50) NOT NULL,
    execution_mode VARCHAR(50) NOT NULL,
    current_step INT NOT NULL DEFAULT 1,
    failure_code VARCHAR(100),
    failure_reason VARCHAR(500),
    verification_status VARCHAR(50),
    submission_attempted BOOLEAN NOT NULL DEFAULT FALSE,
    email_sent BOOLEAN NOT NULL DEFAULT FALSE,
    file_uploaded BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    completed_at TIMESTAMP NULL,
    INDEX idx_cae_app_user (application_id, user_id),
    INDEX idx_cae_exec_run (execution_run_id)
);
